<select name="university[]" class="custom-select d-block w-100" required>
                                  <option value="1">BISE Hyderabad
</option><option value="2">University of Sindh, Jamshoro
</option><option value="3">Agha Khan University, Karachi
</option><option value="4">University of Karachi</option><option value="5">Al-Khair University, AJK
</option><option value="6">Alhamd Islamic University
</option><option value="7">Allama Iqbal Open University Islamabad
</option><option value="8">BIE Karachi 
</option><option value="9">BISE  Gujranwala
</option><option value="10">BISE Abbottabad
</option><option value="11">BISE Bahawalpur
</option><option value="12">BISE Bannu
</option><option value="13">BISE D.G. Khan
</option><option value="14">BISE Faisalabad 
</option><option value="15">BISE MirpurKhas</option><option value="16">BISE Kohat
</option><option value="17">BISE Lahore
</option><option value="18">BISE Larkana
</option><option value="19">BISE MIRPUR, AJK
</option><option value="20">BISE Malakand
</option><option value="21">BISE Mardan
</option><option value="22">BISE Multan
</option><option value="23">BISE Peshawar
</option><option value="24">BISE Quetta
</option><option value="25">BISE Rawalpindi 
</option><option value="26">BISE Sargodha
</option><option value="27">BISE Sukkur
</option><option value="28">BISE Swat
</option><option value="29">BSE Karachi
</option><option value="30">BTE Peshawar
</option><option value="31">BTE Peshawar
</option><option value="32">Bahauddin Zakariya University Multan
</option><option value="33">Bahria University Islamabad
</option><option value="34">Balochistan University of Engineering and Technology
</option><option value="35">Balochistan University of Information Tech. and Management Sciences
</option><option value="36">Baqai Medical University, Karachi
</option><option value="37">CECOS University of Information Technology and Emerging Sciences
</option><option value="38">CFA USA
</option><option value="39">COMSATS Institute of Information Technology
</option><option value="40">City University of Science &amp; Information Technology, Peshawar
</option><option value="41">City University of Science and IT Peshawar
</option><option value="42">College of Buisness Administration&amp; Economics (NCBA&amp;E) Lahore
</option><option value="43">College of Physician and Surgeons Pakistan
</option><option value="44">D. I. H. E. Karachi
</option><option value="45">Dadabhoy Institute of Higher Education, Karachi
</option><option value="46">Dawood College of Engineering &amp; Technology
</option><option value="47">Dow University of Health Sciences
</option><option value="48">FBISE Islamabad
</option><option value="49">Fatima Jinnah Women University, Rawalpindi
</option><option value="50">Federal Urdu University of Arts, Sciences and Technology
</option><option value="51">Forman Christian College, Lahore
</option><option value="52">Foundation University, Islamabad
</option><option value="53">Frontier Women University, Peshawar
</option><option value="54">GIFT University, Gujranwala
</option><option value="55">Gandhara University, Peshawar
</option><option value="56">Georgetown University, Washington
</option><option value="57">Ghulam Ishaq Khan Institute of Engg. Sciences &amp; Technology, Swabi
</option><option value="58">Gomal University D.I.Khan
</option><option value="59">Government College University, Faisalabad
</option><option value="60">Government College University, Lahore
</option><option value="61">Greenwich University, Karachi
</option><option value="62">Hajvery University, Lahore
</option><option value="63">Hamdard University, Karachi
</option><option value="64">Hazara University, Mansehra
</option><option value="65">ICMAP  Karachi
</option><option value="66">Imperial College of Business Studies, Lahore
</option><option value="67">Indus Institute of Higher Education, Karachi
</option><option value="68">Indus Valley School of Art and Architecture, Karachi
</option><option value="69">Institute of Business &amp; Technology BIZTEK, Karachi
</option><option value="70">Institute of Business Administration
</option><option value="71">Institute of Business Management, Karachi
</option><option value="72">Institute of Management Sciences (IMSciences)
</option><option value="73">Institute of Management Sciences, Lahore
</option><option value="74">Institute of Social Studies
</option><option value="75">International Islamic University Islamabad
</option><option value="76">Iqra University, Karachi
</option><option value="77">Iqra University, Quetta
</option><option value="78">Islamia University, Bahawalpur
</option><option value="79">Isra University, Hyderabad
</option><option value="80">Jinnah University for Women, Karachi
</option><option value="81">KASB (Khadim Ali Shah Bukhari) Institute of Technology, Karachi
</option><option value="82">KELLER ISD
</option><option value="83">Karachi Institute of Economics &amp; Technology, Karachi
</option><option value="84">Karakuram International University, Gilgit
</option><option value="85">Khyber Medical University Peshawar
</option><option value="86">King Edward Medical University Lahore
</option><option value="87">Kinnaird College for Women, Lahore
</option><option value="88">Kohat University of Science &amp; Technology, Kohat
</option><option value="89">Lahore College for Women University, Lahore
</option><option value="90">Lahore School of Economics, Lahore
</option><option value="91">Lahore University of Management Sciences, Lahore
</option><option value="92">Lasbela University, Uthal, Balochistan
</option><option value="93">Lasbelaa University of Agriculture, Water &amp; Marine Science, Othal
</option><option value="94">Liaquat University of Medical and Health Sciences, Jamshoro Sindh
</option><option value="95">Mehran University of Engineering &amp; Technology, Jamshoro
</option><option value="96">Mohammad Ali Jinnah University, Karachi
</option><option value="97">Mohi-ud-Din Islamic University, AJK
</option><option value="98">NED University of Engineering &amp; Technology, Karachi
</option><option value="99">NWFP Agriculture University, Peshawar
</option><option value="100">NWFP University of Engineering &amp; Technology, Peshawar
</option><option value="101">National College of Arts, Lahore
</option><option value="102">National Defence University, Islamabad
</option><option value="103">National Institute of Rehabilitation Medicine, Islamabad
</option><option value="104">National Textile University, Faisalabad (Federal Chartered)
</option><option value="105">National University of Computer and Emerging Sciences
</option><option value="106">National University of Computer and Emerging Sciences, Lahore
</option><option value="107">National University of Modern Languages, Islamabad
</option><option value="108">National University of Sciences &amp; Technology , Rawalpindi
</option><option value="109">Newports Institute of Communications and Economics, Karachi
</option><option value="110">Northern University, Nowshera Cantonment
</option><option value="111">Oracle University Dellas, USA
</option><option value="112">Other
</option><option value="113">PBTE Lahore
</option><option value="114">Pakistan Air Force
</option><option value="115">Pakistan Air Force
</option><option value="116">Pakistan Institute of Engineering &amp; Applied Sciences, Islamabad
</option><option value="117">Pakistan Military Academy, Kakul, Abbottabad
</option><option value="118">Pakistan Naval Academy, Karachi
</option><option value="119">Preston Institute of Management Sciences and Technology, Karachi
</option><option value="120">Preston University, Karachi
</option><option value="121">Preston University, Kohat
</option><option value="122">Quaid-e-Awam University of Engineering, Science &amp; Tech, Nawabshah
</option><option value="123">Quaid-i-Azam University, Islamabad
</option><option value="124">Qurtaba University of Science &amp; Information Technology, D. I. Khan
</option><option value="125">Riphah International University, Islamabad
</option><option value="126">SBTE Karachi
</option><option value="127">SZABIST Karachi
</option><option value="128">Sardar Bahadur Khan Women University, Quetta 
</option><option value="129">Sarhad University of Science &amp; Information Technology
</option><option value="130">Shah Abdul Latif University, Khairpur
</option><option value="131">Sindh Agriculture University, Tandojam
</option><option value="132">Sir Syed University of Engg. &amp; Technology, Karachi
</option><option value="133">Tanzeem-Ul-Madaris, Lahore
</option><option value="134">Tarrant County College
</option><option value="135">Textile Institute of Pakistan, Karachi
</option><option value="136">The Superior College, Lahore 
</option><option value="137">The University of Management &amp; Technology, Lahore
</option><option value="138">University College of Education
</option><option value="139">University Law College
</option><option value="140">University of Agriculture, Faisalabad
</option><option value="141">University of Arid Agriculture, Murree Road, Rawalpindi
</option><option value="142">University of Azad Jammu &amp; Kashmir, Muzaffarabad, Azad Kashmir
</option><option value="143">University of Balochistan, Quetta
</option><option value="144">University of Botswana
</option><option value="145">University of Cambridge UK
</option><option value="146">University of Cambridge/ EDEXCEL International, UK
</option><option value="147">University of Central Punjab, Lahore
</option><option value="148">University of East, Hyderabad 
</option><option value="149">University of Education, Lahore
</option><option value="150">University of Engineering &amp; Technology, Lahore 
</option><option value="151">University of Engineering &amp; Technology, Taxila
</option><option value="152">University of Faisalabad
</option><option value="153">University of Gujrat
</option><option value="154">University of Health Sciences, Lahore
</option><option value="155">Air University Islamabad</option>
<option value="156">University of Lahore
</option><option value="157">University of London 
</option><option value="158">University of Malakand
</option><option value="159">University of Management and Technology
</option><option value="160">University of Peshawar
</option><option value="161">University of Sargodha
</option><option value="162">Abasyn University Peshawar</option>
<option value="163">University of South Asia, Lahore
</option><option value="164">University of Veterinary and Animal Sciences, Lahore
</option><option value="165">University of the Punjab, Lahore
</option><option value="166">Virtual University of Pakistan, Lahore
</option><option value="167">Zia-ud-Din Medical University, Karachi
</option><option value="168">Shaheed Benazir Bhutto University of Veterinary and Animal Science Sakrand</option>
<option value="169">DHA SUFFA UNIVERSITY</option>
<option value="170">SINDH MADRESSATUL ISLAM UNIVERSITY (SMIU)</option>
<option value="171">The Shaikh Ayaz University Shikarpur</option>
<option value="172">Shaheed Benazir Bhutto University</option>
<option value="other">other</option> </select>